title: Glenbain Goodies
url: https://www.glenbaingoodies.ca
baseurl: ""   # MUST be empty for custom domain


collections:
  categories:
    output: true
  recipes:
    output: true
    permalink: /:collection/:name/
